Promote pipeline update

diff --git a/.github/workflows/promote.yml b/.github/workflows/promote.yml
--- a/.github/workflows/promote.yml
+++ b/.github/workflows/promote.yml
@@ -21,8 +21,8 @@ on:
         required: true
 
 env:
-  REPOSITORY_URL: 'https://maven.pkg.github.com/'
-  UPSTREAM_REPOSITORY_URL: 'https://oss.sonatype.org/'
+  REPOSITORY_URL: 'https://maven.pkg.github.com'
+  UPSTREAM_REPOSITORY_URL: 'https://oss.sonatype.org'
   PACKAGE_SUFFIXES: '-javadoc.jar,-javadoc.jar.asc,-sources.jar,-sources.jar.asc,.jar,.jar.asc,.pom,.pom.asc'
   PACKAGE: 'com.epam.reportportal'
 
@@ -40,14 +40,14 @@ jobs:
 
       - name: Get variables
         run: |
-          echo "ARTIFACT=`echo ${{ github.repository }} | cut -d/ -f2-`" >> $GITHUB_ENV
+          echo "ARTIFACT=`echo ${{ github.repository }} | cut -d/ -f2- | awk '{print tolower($0)}'`" >> $GITHUB_ENV
           echo "PACKAGE_PATH=`echo ${{ env.PACKAGE }} | sed 's/\./\//g'`" >> $GITHUB_ENV
 
       - name: Upload package
         run: |
           IFS=',' read -a files <<< '${{ env.PACKAGE_SUFFIXES }}'
           for f in ${files[@]}; do
-            export URL="${{ env.REPOSITORY_URL }}${{ github.repository }}/${PACKAGE_PATH}/${ARTIFACT}/${{ github.event.inputs.version }}/${ARTIFACT}-${{ github.event.inputs.version }}${f}"
+            export URL="${{ env.REPOSITORY_URL }}/${{ github.repository }}/${PACKAGE_PATH}/${ARTIFACT}/${{ github.event.inputs.version }}/${ARTIFACT}-${{ github.event.inputs.version }}${f}"
             echo "Downloading artifact: ${URL}"
             curl -f -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s -O -L "${URL}"
           done
@@ -56,15 +56,29 @@ jobs:
           echo "${files[@]}"
 
           echo 'Bundle generation'
-          export BUNDLE_FILE="${ARTIFACT}-${{ github.event.inputs.version }}-bundle.jar"
+          export BUNDLE_FILE="bundle.jar"
           jar -cvf ${BUNDLE_FILE} "${files[@]}"
 
           echo 'Bundle upload'
           curl -u ${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }} -L \
-            --request POST '${{ env.UPSTREAM_REPOSITORY_URL }}service/local/staging/bundle_upload' \
-            --form "file=@${BUNDLE_FILE}" \
-            | jq -r '.repositoryUris[0]' \
-            | (read r; echo "NEXUS_REPOSITORY=${r}" >> $GITHUB_ENV)
+            --request POST '${{ env.UPSTREAM_REPOSITORY_URL }}/service/local/staging/bundle_upload' \
+            --form "file=@${BUNDLE_FILE}" >response.json
+
+          response_type=`jq type response.json || echo ''`
+          if [ -z "$response_type" ]; then
+            echo 'ERROR: Response is not JSON!' 1>&2
+            cat response.json 1>&2
+            exit 1
+          fi
+
+          repo=`jq -r '.repositoryUris[0]' response.json`
+          if [ -z "$repo" ]; then
+            echo 'Unable to upload bundle' 1>&2
+            cat response.json 1>&2
+            exit 1
+          fi
+
+          echo "NEXUS_REPOSITORY=${repo}" >> $GITHUB_ENV
 
       - name: Get repository variables
         run: |
@@ -80,7 +94,7 @@ jobs:
             sleep $SLEEP_TIME
             curl -f -s -u ${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }} -L \
               --header 'Accept: application/json' \
-              ${{ env.UPSTREAM_REPOSITORY_URL }}service/local/staging/repository/${NEXUS_REPOSITORY_NAME} >result.json
+              ${{ env.UPSTREAM_REPOSITORY_URL }}/service/local/staging/repository/${NEXUS_REPOSITORY_NAME} >result.json
 
             is_closed=`jq -r '.type' result.json`
             is_transitioning=`jq -r '.transitioning' result.json`
@@ -96,8 +110,8 @@ jobs:
             curl -f -u ${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }} -L \
               --header 'Content-Type: application/json' \
               --data-raw "{\"data\":{\"stagedRepositoryIds\":[\"${NEXUS_REPOSITORY_NAME}\"], \"description\":\"Releasing ${{ github.event.inputs.version }}\"}}" \
-              --request POST ${{ env.UPSTREAM_REPOSITORY_URL }}service/local/staging/bulk/promote
+              --request POST ${{ env.UPSTREAM_REPOSITORY_URL }}/service/local/staging/bulk/promote
           else
-            echo "Verification failed, please check the bundle"
+            echo 'Verification failed, please check the bundle' 1>&2
             exit 1
           fi
